language: cpp

coḿpiler:
  - clang
  - gcc

addons:
  apt:
    packages: &common_packages
      - doxygen
      - graphviz
      - lcov

matrix:
  fast_finish: true
  include:

    ##########################################################################
    # Clang on OSX
    ##########################################################################

    # XCode 9.4
    - env: COMPILER=clang++ BUILD_TYPE=Debug COVERAGE=OFF
      os: osx
      osx_image: xcode9.4
      compiler: clang
      addons:
        homebrew:
          update: true
          packages:
            - *common_packages
            - qt

    - env: COMPILER=clang++ BUILD_TYPE=Release COVERAGE=OFF
      os: osx
      osx_image: xcode9.4
      compiler: clang
      addons:
        homebrew:
          update: true
          packages:
            - *common_packages
            - qt

    # XCode 11
    - env: COMPILER=clang++ BUILD_TYPE=Debug COVERAGE=OFF
      os: osx
      osx_image: xcode11
      compiler: clang
      addons:
        homebrew:
          packages:
            - *common_packages
            - qt

    - env: COMPILER=clang++ BUILD_TYPE=Release COVERAGE=OFF
      os: osx
      osx_image: xcode11
      compiler: clang
      addons:
        homebrew:
          packages:
            - *common_packages
            - qt

    ##########################################################################
    # Clang on Linux
    ##########################################################################
    - env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
        - BUILD_TYPE=Debug
        - COVERAGE=OFF
      os: linux
      dist: trusty
      name: "Clang Trusty Debug"
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - *common_packages
            - qt5-default

    - env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
        - BUILD_TYPE=Release
        - COVERAGE=OFF
      os: linux
      dist: trusty
      name: "Clang Trusty Release"
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - *common_packages
            - qt5-default

    - env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
        - BUILD_TYPE=Debug
        - COVERAGE=OFF
      os: linux
      dist: xenial
      name: "Clang Xenial Debug"
      addons:
        apt:
          packages:
            - *common_packages
            - qt5-default

    - env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
        - BUILD_TYPE=Release
        - COVERAGE=OFF
      os: linux
      dist: xenial
      name: "Clang Xenial Release"
      addons:
        apt:
          packages:
            - *common_packages
            - qt5-default

    - env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
        - BUILD_TYPE=Debug
        - COVERAGE=ON
      os: linux
      dist: bionic
      name: "Clang Bionic Debug"
      addons:
        apt:
          packages:
            - *common_packages
            - qt5-default

    - env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
        - BUILD_TYPE=Release
        - COVERAGE=OFF
      os: linux
      dist: bionic
      name: "Clang Bionic Release"
      addons:
        apt:
          packages:
            - *common_packages
            - qt5-default

    ##########################################################################
    # GCC on Linux
    ##########################################################################
    - env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - BUILD_TYPE=Debug
        - COVERAGE=OFF
      os: linux
      dist: trusty
      name: "GCC Trusty Debug"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - *common_packages
            - qt5-default

    - env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - BUILD_TYPE=Release
        - COVERAGE=OFF
      os: linux
      dist: trusty
      name: "GCC Trusty Release"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - *common_packages
            - qt5-default

    - env:
        - MATRIX_EVAL="CC=gcc && CXX=g++"
        - BUILD_TYPE=Debug
        - COVERAGE=OFF
      os: linux
      dist: xenial
      name: "GCC Xenial Debug"
      addons:
        apt:
          packages:
            - *common_packages
            - qt5-default

    - env:
        - MATRIX_EVAL="CC=gcc && CXX=g++"
        - BUILD_TYPE=Release
        - COVERAGE=OFF
      os: linux
      dist: xenial
      name: "GCC Xenial Release"
      addons:
        apt:
          packages:
            - *common_packages
            - qt5-default

    - env:
        - MATRIX_EVAL="CC=gcc && CXX=g++"
        - BUILD_TYPE=Debug
        - COVERAGE=OFF
      os: linux
      dist: bionic
      name: "GCC Bionic Debug"
      addons:
        apt:
          packages:
            - *common_packages
            - qt5-default

    - env:
        - MATRIX_EVAL="CC=gcc && CXX=g++"
        - BUILD_TYPE=Release
        - COVERAGE=OFF
      os: linux
      dist: bionic
      name: "GCC Bionic Release"
      addons:
        apt:
          packages:
            - *common_packages
            - qt5-default

install:
  - JOBS=2
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      wget -O cmake.sh https://cmake.org/files/v3.10/cmake-3.10.3-Linux-x86_64.sh
      sudo sh cmake.sh --skip-license --exclude-subdir --prefix=/usr/local
      export PATH=/usr/local/bin:${PATH}
    else
      brew install cmake || brew upgrade cmake
      QT5_CMAKE_PREFIX=/usr/local/opt/qt/lib/cmake/Qt5
      export QT5_CMAKE_PREFIX
    fi
  - cmake --version
  - export COVERAGE
  - eval "${MATRIX_EVAL}"

script:
  - mkdir build
  - cd build
  - echo "Building $BUILD_TYPE with QT prefix $QT5_CMAKE_PREFIX - Coverage is $COVERAGE"
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DENABLE_COVERAGE=$COVERAGE -DQt5_DIR=$QT5_CMAKE_PREFIX
  - cmake --build . -- -j 2

  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then ( sudo Xvfb :99 -ac -screen 0 1024x768x8; ctest )& fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then (CTEST_OUTPUT_ON_FAILURE=1 xvfb-run ctest) fi

after_success:
    # Creating report
  - |
    if [[ "${COVERAGE}" == "ON" ]]; then
      cd ${TRAVIS_BUILD_DIR}
      lcov --directory . --capture --output-file coverage.info # capture coverage info
      lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
      lcov --list coverage.info #debug info
      # Uploading report to CodeCov
      - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
    fi