image: Visual Studio 2017

configuration:
  - Release

environment:
  matrix:
  - CMAKE_GENERATOR: "Visual Studio 15 2017 Win64"
    QT5: C:\Qt\5.9.5\msvc2017_64

before_build:
- set Path=%QT5%\bin;%Path%
- cmake -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE -DBUILD_SHARED_LIBS=TRUE -G "%CMAKE_GENERATOR%" "-DCMAKE_PREFIX_PATH=%QT5%"

build:
  project: $(APPVEYOR_BUILD_FOLDER)\$(APPVEYOR_PROJECT_NAME).sln

test_script:
  - '%APPVEYOR_BUILD_FOLDER%\%CONFIGURATION%\aide_ut.exe'
