name: "Setup dependencies"
description: "Install required dependencies"
inputs:
  cmake_version:
    description: "Version of CMake to install"
    default: 4.x
  qt_version:
    description: "Version of Qt to install"
    default: 6.9.2
runs:
  using: "composite"
  steps:
    - name: Setup Windows environment
      if: runner.os == 'Windows'
      shell: pwsh -Command "$PSVersionTable; $PSNativeCommandUseErrorActionPreference = $true; $ErrorActionPreference = 'Stop'; & '{0}'"
      run: |
        $vswherePath = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
        $installationPath = & $vswherePath -latest -property installationPath
        & "${env:COMSPEC}" /s /c "`"$installationPath\Common7\Tools\vsdevcmd.bat`" -arch=x64 -no_logo && set" | foreach-object {
          $name, $value = $_ -split '=', 2
          echo "$name=$value" >> $env:GITHUB_ENV
        }

    - name: Install Conan
      uses: conan-io/setup-conan@v1.4.0
      with:
        cache_packages: true

    - name: Setup ccache
      uses: hendrikmuhs/ccache-action@v1.2.24
    
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: ${{inputs.cmake_version}}

    - name: Print CMake version
      shell: bash
      run: cmake --version

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        cache: true
        version: ${{ inputs.qt_version }}
        aqtversion: '==3.1.*'
