name: CI - ABI compliance check

on:
  workflow_call:

jobs:
  build:
    name: ${{ matrix.os }}, ${{ matrix.cmake_name }}, ${{ matrix.qt_name }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
        cmake: [4.x]
        qt: ["6.5.0"]

        include:
          - cmake: 4.x
            cmake_name: CMake Latest

          - qt: "6.5.0"
            qt_name: Qt6

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - id: setup_deps
        uses: ./.github/actions/setup_deps
        with:
          cmake_version: ${{matrix.cmake}}
          qt_version: ${{ matrix.qt }}

      - name: Install apt dependencies
        if: runner.os == 'Linux'
        run: sudo apt install abi-dumper abi-compliance-checker

      - name: Select base sha
        if: github.event_name == 'pull_request'
        id: base_sha
        run: |
          echo "SHA=-Daide_ABI_BASE_HASH=${{ github.event.pull_request.base.sha }}" >> $GITHUB_OUTPUT

      # Shared Debug with ABI compliance check
      - name: "ABI Compliance Check: Configure"
        run: cmake --preset ci-abi-check-unix-shared-debug ${{ steps.base_sha.outputs.SHA }}

      - name: "ABI Compliance Check: Build"
        run: cmake --build --preset  build-ci-abi-check-unix-shared-debug

      - name: Upload ABI compliance report
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: abi_compliance_report
          path: |
            build/ci-abi-check-unix-shared-debug/compat_reports/libAide/**/*.html
            build/ci-abi-check-unix-shared-debug/logs/
