name: CI - ABI compliance check

on:
  workflow_call:

jobs:
  build:
    name: ${{ matrix.os }}, ${{ matrix.cmake_name }}, ${{ matrix.qt_name }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-24.04 ]
        cmake: [ 3.x ]
        qt: [ "6.5.0" ]

        include:
          - cmake: 3.x
            cmake_name: CMake Latest

          - qt: "6.5.0"
            qt_name: Qt6

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: seanmiddleditch/gha-setup-ninja@v5

      - name: Setup Windows environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install pip dependencies
        run: |
          pip3 install wheel setuptools
          pip3 install conan

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: ${{matrix.cmake}}

      - name: Print CMake version
        run: cmake --version

      - name: Install apt dependencies
        if: runner.os == 'Linux'
        run: sudo apt install lcov ^libxcb-* abi-dumper abi-compliance-checker

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.qt }}
          aqtversion: '==3.1.*'

      - name: Select base sha
        if: github.event_name == 'pull_request'
        id: base_sha
        run: |
          echo "SHA=-Daide_ABI_BASE_HASH=${{ github.event.pull_request.base.sha }}" >> $GITHUB_OUTPUT

      # Shared Debug with ABI compliance check
      - name: "ABI Compliance Check: Configure"
        run: cmake --preset ci-abi-check-unix-shared-debug ${{ steps.base_sha.outputs.SHA }}

      - name: "ABI Compliance Check: Build"
        run: cmake --build --preset  build-ci-abi-check-unix-shared-debug

      - name: Upload ABI compliance report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: abi_compliance_report
          path: |
            build/ci-abi-check-unix-shared-debug/compat_reports/libAide/**/*.html
            build/ci-abi-check-unix-shared-debug/logs/
