name: CI - Build and Test

on:
  workflow_call:

jobs:
  build:
    name: ${{ matrix.os }}, ${{ matrix.cmake_name }}, ${{ matrix.qt_name }}
    permissions:
      id-token: write

    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-24.04 ]
        cmake: [ 3.25, 4.x ]
        qt: [ "5.15.2", "6.5.0" ]

        include:
          - os: windows-latest
            CXX: cl

          - cmake: 3.25
            cmake_name: CMake 3.25
          - cmake: 4.x
            cmake_name: CMake Latest

          - qt: "5.15.2"
            qt_name: Qt5
          - qt: "6.5.0"
            qt_name: Qt6

          - qt: "6.5.0"
            cmake: 4.x
            os: ubuntu-24.04
            COVERAGE: ON
            GCOV_TOOL: gcov

        exclude:
          - os: macos-latest
            qt: 5.15.2

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    env:
      # CMake 3.15 doesn't detect Visual Studio correctly without these.
      CXX: ${{ matrix.CXX }}
      CC: ${{ matrix.CXX }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: seanmiddleditch/gha-setup-ninja@v5

      - name: Setup Windows environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
          cache: 'pip'

      - name: Install pip dependencies
        run: |
          pip3 install wheel setuptools
          pip3 install conan

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: ${{matrix.cmake}}

      - name: Print CMake version
        run: cmake --version

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          cache: true
          version: ${{ matrix.qt }}
          aqtversion: '==3.1.*'

      - name: Select preset
        id: preset
        run: |
          if [[ "${{ runner.os }}" == "Linux" || "${{ runner.os }}" == "macOS" ]]; then
            echo "PRESET=workflow-ci-strict-unix" >> $GITHUB_OUTPUT
          else
            echo "PRESET=workflow-ci-strict-windows" >> $GITHUB_OUTPUT
          fi

      # Static Debug
      - name: "Static Debug: Workflow"
        run: cmake --workflow --preset ${{ steps.preset.outputs.PRESET }}-static-debug
        env:
          QT_QPA_PLATFORM: offscreen

      # Shared Debug
      - name: "Shared Debug: Workflow"
        run: cmake --workflow --preset ${{ steps.preset.outputs.PRESET }}-shared-debug
        env:
          QT_QPA_PLATFORM: offscreen

      # Static Release
      - name: "Static Release: Workflow"
        run: cmake --workflow --preset ${{ steps.preset.outputs.PRESET }}-static-release
        env:
          QT_QPA_PLATFORM: offscreen

      # Shared Release
      - name: "Shared Release: Workflow"
        run: cmake --workflow --preset ${{ steps.preset.outputs.PRESET }}-shared-release
        env:
          QT_QPA_PLATFORM: offscreen

      - name: Upload Unit Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test_results_${{ matrix.os }}_cmake-${{ matrix.cmake }}_qt-${{ matrix.qt }}
          path: build*/**/*.xml

  publish-test-results:
    name: "Publish Unit Test Results from ${{ matrix. os }}"
    needs: build
    if: always()

    strategy:
      matrix:
        os: [ ubuntu-24.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Publish Unit Test Results ${{ matrix.os }}
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: Unit Test Results ${{ matrix.os }}
          comment_mode: always
          files: artifacts/test_results_${{ matrix.os}}*/**/tests/ut/*.xml
          report_individual_runs: true
          deduplicate_classes_by_file_name: false

