name: Check third party licenses

on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  check_license:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v6
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
          token: ${{ secrets.token }}
          fetch-depth: 0

      - id: setup_deps
        uses: ./.github/actions/setup_deps

      - name: Check third party licenses
        run: cmake --workflow --preset workflow-ci-license-check-unix

      - uses: EndBug/add-and-commit@v10
        id: commit
        with:
          add: '3rd-party-licenses.md'
          author_name: License Check Robot
          author_email: bot@github.com
          message: 'chore: automatic third party licenses update'
