name: CI - Weekly

on:
  schedule:
    - cron: "37 16 * * 3"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ci_build_and_test:
    uses: ./.github/workflows/build_and_test.yml

  check_third_party_license_availability:
    uses: ./.github/workflows/check_licenses.yml
