name: CI - Generate coverage report

on:
  workflow_call:

jobs:
  build:
    name: ${{ matrix.os }}, ${{ matrix.cmake_name }}, ${{ matrix.qt_name }}
    permissions:
      id-token: write

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
        cmake: [4.x]
        qt: [6.9.2]

        include:
          - cmake: 4.x
            cmake_name: CMake Latest

          - qt: 6.9.2
            qt_name: Qt6

          - qt: 6.9.2
            cmake: 4.x
            os: ubuntu-24.04
            GCOV_TOOL: gcov

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - id: setup_deps
        uses: ./.github/actions/setup_deps
        with:
          cmake_version: ${{matrix.cmake}}
          qt_version: ${{ matrix.qt }}

      - name: Install and cache apt dependencies
        if: runner.os == 'Linux'
        run: sudo apt install lcov

      # Static Debug
      - name: "Coverage Workflow (static debug)"
        run: cmake --workflow --preset workflow-ci-coverage-unix
        env:
          QT_QPA_PLATFORM: offscreen

      - name: Generate and coverage reports
        working-directory: build/ci-coverage-unix
        run: |
          lcov --gcov-tool gcov --directory . --capture --output-file coverage.info # capture coverage info
          lcov --gcov-tool gcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
          lcov --gcov-tool gcov --list coverage.info #debug info

      - name: Upload coverage reports
        uses: codecov/codecov-action@v6
        with:
          use_oidc: true
