name: CD - Deploy to Github Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - uses: seanmiddleditch/gha-setup-ninja@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install pip dependencies
        run: |
          pip3 install wheel setuptools
          pip3 install conan

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: 4.x

      - name: Print CMake version
        run: cmake --version

      - name: Install apt dependencies
        if: runner.os == 'Linux'
        run: sudo apt install lcov ^libxcb-*

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.0'
          aqtversion: '==3.1.*'

      # Shared Release with packaging
      - name: "Shared Release: Configure and build with preset"
        run: cmake --workflow --preset workflow-ci-deploy-unix-shared-release
        env:
          QT_QPA_PLATFORM: offscreen

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload Release Asset
        id: upload-release-asset
        uses: csexton/release-asset-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          pattern: "./build/ci-deploy-unix-shared-release/aide*.tar.gz"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-url: ${{ steps.get_release.outputs.upload_url }}
