name: Publish Doxygen GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - id: setup_deps
        uses: ./.github/actions/setup_deps

      - name: Install Doxygen
        run: sudo apt install doxygen graphviz -y

      - name: Build doxygen documentation
        run: cmake --workflow --preset workflow-ci-doxygen-unix

      - name: Publish doxygen documentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: build/ci-doxygen-unix/aide/doc/html
          github_token: ${{ secrets.GITHUB_TOKEN }}
