name: Build standalone and test installed lib

on:
  workflow_call:

jobs:
  build_standalone:
    name: ${{ matrix.qt_name }}
    strategy:
      fail-fast: false
      matrix:
        qt: [6.8.3]

        include:
          - qt: 6.8.3
            qt_name: Qt6

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - id: setup_deps
        uses: ./.github/actions/setup_deps
        with:
          qt_version: ${{ matrix.qt }}

      - name: "Static Release: Workflow lib install"
        working-directory: aide
        run: cmake --workflow --preset workflow-ci-install-lib-unix-static-release

      - name: "Static Release: Workflow test installed lib"
        working-directory: tests
        run: cmake --workflow --preset workflow-ci-install-test-unix-static-release
        env:
          QT_QPA_PLATFORM: offscreen

      - name: "Shared Release: Workflow lib install"
        working-directory: aide
        run: cmake --workflow --preset workflow-ci-install-lib-unix-shared-release

      - name: "Shared Release: Test installed lib"
        working-directory: tests
        run: cmake --workflow --preset workflow-ci-install-test-unix-shared-release
        env:
          QT_QPA_PLATFORM: offscreen

      - name: Upload Unit Test Results
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: test_results_installed_lib-qt-${{ matrix.qt }}
          path: tests/build*/**/*.xml

  publish-test-results:
    name: "Publish Unit Test Results from installed lib"
    needs: build_standalone
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v8
        with:
          path: artifacts

      - name: Publish Unit Test Results installed lib
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: Unit Test Results install lib
          comment_mode: always
          files: artifacts/test_results_installed_lib-*/build*/ci-*/**/*.xml
          report_individual_runs: true
          deduplicate_classes_by_file_name: false
