name: Build standalone and test installed lib

on: [push]

jobs:
  build:
    name: ${{ matrix.qt_name }}
    strategy:
      fail-fast: false
      matrix:
        qt: [ "5.15.2", "6.5.0" ]

        include:
          - qt: "5.15.2"
            qt_name: Qt5
          - qt: "6.5.0"
            qt_name: Qt6

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.6

    - name: Install dependencies
      run: |
        pip3 install wheel setuptools
        pip3 install --upgrade -r requirements.txt
        sudo apt install ^libxcb-*

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ matrix.qt }}
        aqtversion: '==3.1.*'

    - name: "Static Release: Configure"
      working-directory: aide
      run: cmake -S . -B build-static-rel -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=~/.local/build-static-rel/
    - name: "Static Release: Build and install"
      working-directory: aide
      run:  cmake --build build-static-rel --target install --parallel
    - name: "Static Release: Configure tests"
      working-directory: tests
      run: cmake -S . -B build-static-rel -DCMAKE_INSTALL_PREFIX=~/.local/build-static-rel -DUNIT_TESTS_RUN_ON_CI=1
    - name: "Static Release: Build tests"
      working-directory: tests
      run: cmake --build build-static-rel --parallel
    - name: "Static Release: Run tests"
      working-directory: tests/build-static-rel
      run: ctest
      env:
        QT_QPA_PLATFORM: offscreen

    - name: "Shared Release: Configure"
      working-directory: aide
      run: cmake -S . -B build-shared-rel -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=~/.local/build-static-rel/
    - name: "Shared Release: Build and install"
      working-directory: aide
      run:  cmake --build build-shared-rel --target install --parallel
    - name: "Shared Release: Configure tests"
      working-directory: tests
      run: cmake -S . -B build-shared-rel -DCMAKE_INSTALL_PREFIX=~/.local/build-static-rel -DUNIT_TESTS_RUN_ON_CI=1
    - name: "Shared Release: Build tests"
      working-directory: tests
      run: cmake --build build-shared-rel --parallel
    - name: "Shared Release: Run tests"
      working-directory: tests/build-shared-rel
      run: ctest
      env:
        QT_QPA_PLATFORM: offscreen

    - name: Upload Unit Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test_results_installed_lib
        path: tests/build*rel/**/*.xml

  publish-test-results:
    name: "Publish Unit Test Results from installed lib"
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Publish Unit Test Results installed lib
        uses: EnricoMi/publish-unit-test-result-action@v1.4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: Unit Test Results install lib
          hide_comments: all but latest
          comment_on_pr: true
          files: artifacts/test_results_installed_lib/build*rel/**/*.xml
          report_individual_runs: true
          deduplicate_classes_by_file_name: false
