name: CI - Static Analyzer

on:
  workflow_call:

jobs:
  build:
    name: ${{ matrix.os }}, ${{ matrix.cmake_name }}, ${{ matrix.qt_name }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-24.04]
        cmake: [4.x]
        qt: ["5.15.2", "6.5.0"]

        include:
          - cmake: 4.x
            cmake_name: CMake Latest

          - qt: "5.15.2"
            qt_name: Qt5
          - qt: "6.5.0"
            qt_name: Qt6
        exclude:
          - os: macos-latest
            qt: 5.15.2

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Windows environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.x
      - name: Install pip dependencies
        run: |
          pip3 install wheel setuptools
          pip3 install conan

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: ${{matrix.cmake}}

      - name: Print CMake version
        run: cmake --version

      - name: Install apt dependencies
        if: runner.os == 'Linux'
        run: sudo apt install cppcheck ^libxcb-*

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ matrix.qt }}
          aqtversion: '==3.1.*'

      # Static Debug
      - name: "Static Debug: Static analysis"
        run: cmake --workflow --preset=workflow-ci-static-unix-static-debug
        env:
          QT_QPA_PLATFORM: offscreen
